name: Deploy Production

on:
  workflow_run:
    workflows: ["Docker Build and Push"]
    branches: [main]
    types:
      - completed

jobs:
  deploy-prod:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to Prod Server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd ${{ secrets.SERVER_PATH_PROD }}
            docker compose pull
            docker compose up -d
